# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hkbu-ar-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: ar-backend

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          version: 11

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: ar-backend/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm prune --prod

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A31FFC4F1BA84DCF862FB6E40FCCA8ED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B8196968E3C8440D8BED355C293BB69D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_728D2D3760EB499F98D8FAA8F56F05D9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: hkbu-ar-backend
          slot-name: Production
          package: ar-backend
